name: s3
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Check if first deployment
      id: first_deploy
      run: |
        if aws s3 ls s3://mangeshport/; then
          echo "Existing deployment"
          echo "first_deploy=false" >> $GITHUB_ENV
        else
          echo "First deployment"
          echo "first_deploy=true" >> $GITHUB_ENV
        fi

    - name: Initial S3 Sync (all files)
      if: env.first_deploy == 'true'
      run: |
        aws s3 sync . s3://mangeshport/
      continue-on-error: true

    - name: Get list of changed files
      if: env.first_deploy == 'false'
      id: changed_files
      run: |
        git diff --name-only HEAD^ HEAD > changed_files.txt
        cat changed_files.txt

    - name: Sync updated files to S3
      if: env.first_deploy == 'false'
      run: |
        while read file; do
          if [ -f "$file" ]; then
            aws s3 cp "$file" "s3://mangeshport/$file"
          fi
        done < changed_files.txt
